[box] boxSizing Mixin 개선
JaesunPark/pullRequest pull request #6
Opened 2017-08-14 06:21 UTC by cjxellos

boxSizing Mixin을 개선하였습니다.

리뷰 좀 부탁드립니다!!

2017-08-14 06:23 UTC, JaesunPark commented on example.scss
> +@mixin boxSizing($box: border-box) {
Mixin 이름이 너무 길지 않나요?

2017-08-14 06:25 UTC, cjxellos commented on example.scss
> +@mixin boxSizing($box: border-box) {
@JaesunPark 
음..
그런가요?

이게 최선이라고 생각했는데 ㅠ

2017-08-14 06:25 UTC, JaesunPark requested changes
Mixin 네이밍에 대해 조금 더 생각하고 수정해주셨으면 좋겠습니다.

2017-08-14 06:29 UTC, JaesunPark approved these changes

2017-08-14 06:29 UTC, JaesunPark commented on example.scss
> +@mixin box($box: border-box) {
@cjxellos 제가 원하던 답입니다.
고생하셨습니다.

2017-08-14 06:29 UTC, merged

2017-08-14 06:52 UTC, JaesunPark commented on example.scss
> +@mixin box($box: border-box) {
테스트로 이슈를 등록해보겠습니다.
#7

2017-08-15 13:21 UTC, JaesunPark commented on example.scss
> +@mixin boxSizing($box: border-box) {
`@mixin Boxsizing($box: border-box){`

2017-08-15 13:21 UTC, JaesunPark commented on example.scss
> +@mixin boxSizing($box: border-box) {
dd

2017-08-15 13:21 UTC, JaesunPark commented on example.scss
> -@mixin boxSizing {
dddd